//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("0.1.90.915")]
[assembly: AssemblyFileVersion("0.1.90.915")]
[assembly: AssemblyProduct("Lottie Windows")]
[assembly: AssemblyCopyright("Microsoft 2018")]
[assembly: AssemblyDescription("Command line Lottie code generator tool")]

