#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include "ICompositionSource.h"

namespace Compositions 
{
ref class MyComposition sealed : public ICompositionSource
{
public:
    virtual bool TryCreateInstance(
        Windows::UI::Composition::Compositor^ compositor,
        Windows::UI::Composition::Visual^* rootVisual,
        Windows::Foundation::Numerics::float2* size,
        Windows::UI::Composition::CompositionPropertySet^* progressPropertySet,
        Windows::Foundation::TimeSpan* duration,
        Platform::Object^* diagnostics);
};
}