#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compositions
{
	ref class BirthdayCake sealed : public Microsoft::UI::Xaml::Controls::CompositionPlayer::ICompositionSource
	{
	public:
		virtual bool TryCreateInstance(
			Windows::UI::Composition::Compositor^ compositor,
			Windows::UI::Composition::Visual^* rootVisual,
			Windows::Foundation::Numerics::float2* size,
			Windows::Foundation::TimeSpan* duration,
			Platform::Object^* diagnostics);
	};
}