//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Host = Microsoft_UI_Xaml_Controls;
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace Compositions
{
    sealed class Empty_box : Host.ICompositionSource
    {
        public bool TryCreateInstance(
            Compositor compositor,
            out Visual rootVisual,
            out Vector2 size,
            out CompositionPropertySet progressPropertySet,
            out TimeSpan duration,
            out object diagnostics)
        {
            rootVisual = Instantiator.InstantiateComposition(compositor);
            size = new Vector2(120, 120);
            progressPropertySet = rootVisual.Properties;
            duration = TimeSpan.FromTicks(20000000);
            diagnostics = null;
            return true;
        }

        sealed class Instantiator
        {
            const long c_durationTicks = 20000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionColorBrush _animatedColorBrush_AlmostGray_FF868686_to_TransparentAlmostGray_00868686;
            CompositionColorBrush _animatedColorBrush_White_to_TransparentWhite;
            CompositionColorBrush _colorBrush_AlmostLightGray_FFCCD1D9;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_3;
            LinearEasingFunction _linearEasingFunction;
            ContainerVisual _root;
            ExpressionAnimation _scalarExpressionAnimation;
            StepEasingFunction _stepEasingFunction;

            // Root.ruoi
            //   Root.Shape Layer 2
            //     Group: Group 6
            //       Path 1
            CompositionColorBrush AnimatedColorBrush_AlmostDarkGray_FF9F9F9F_to_TransparentAlmostDarkGray_009F9F9F()
            {
                var result = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x9F, 0x9F, 0x9F));
                result.StartAnimation("Color", ColorAnimation_AlmostDarkGray_FF9F9F9F_to_TransparentAlmostDarkGray_009F9F9F());
                var controller = result.TryGetAnimationController("Color");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            CompositionColorBrush AnimatedColorBrush_AlmostGray_FF868686_to_TransparentAlmostGray_00868686()
            {
                var result = _animatedColorBrush_AlmostGray_FF868686_to_TransparentAlmostGray_00868686 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x86, 0x86, 0x86));
                result.StartAnimation("Color", ColorAnimation_AlmostGray_FF868686_to_TransparentAlmostGray_00868686());
                var controller = result.TryGetAnimationController("Color");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            CompositionColorBrush AnimatedColorBrush_White_to_TransparentWhite()
            {
                var result = _animatedColorBrush_White_to_TransparentWhite = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF));
                result.StartAnimation("Color", ColorAnimation_White_to_TransparentWhite());
                var controller = result.TryGetAnimationController("Color");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostDarkGray_FF9F9F9F_to_TransparentAlmostDarkGray_009F9F9F()
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                // AlmostDarkGray_FF9F9F9F
                result.InsertKeyFrame(0, Color.FromArgb(0xFF, 0x9F, 0x9F, 0x9F), _linearEasingFunction);
                // AlmostDarkGray_FF9F9F9F
                result.InsertKeyFrame(0.699999988F, Color.FromArgb(0xFF, 0x9F, 0x9F, 0x9F), _linearEasingFunction);
                // TransparentAlmostDarkGray_009F9F9F
                result.InsertKeyFrame(0.980000019F, Color.FromArgb(0x00, 0x9F, 0x9F, 0x9F), CubicBezierEasingFunction_1());
                return result;
            }

            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostGray_FF868686_to_TransparentAlmostGray_00868686()
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                // AlmostGray_FF868686
                result.InsertKeyFrame(0, Color.FromArgb(0xFF, 0x86, 0x86, 0x86), _linearEasingFunction);
                // AlmostGray_FF868686
                result.InsertKeyFrame(0.699999988F, Color.FromArgb(0xFF, 0x86, 0x86, 0x86), _linearEasingFunction);
                // TransparentAlmostGray_00868686
                result.InsertKeyFrame(0.980000019F, Color.FromArgb(0x00, 0x86, 0x86, 0x86), _cubicBezierEasingFunction_1);
                return result;
            }

            // Color
            ColorKeyFrameAnimation ColorAnimation_White_to_TransparentWhite()
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                // White
                result.InsertKeyFrame(0, Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF), _linearEasingFunction);
                // White
                result.InsertKeyFrame(0.699999988F, Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF), _linearEasingFunction);
                // TransparentWhite
                result.InsertKeyFrame(0.980000019F, Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF), _cubicBezierEasingFunction_1);
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 9
            //         Path 1
            CompositionColorBrush ColorBrush_AlmostLavender_FFE6E9EC()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xE6, 0xE9, 0xEC));
            }

            CompositionColorBrush ColorBrush_AlmostLightGray_FFCCD1D9()
            {
                return _colorBrush_AlmostLightGray_FFCCD1D9 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xCC, 0xD1, 0xD9));
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 8
            //         Path 1
            CompositionColorBrush ColorBrush_AlmostWhiteSmoke_FFF4F4F4()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF4, 0xF4, 0xF4));
            }

            // Root.ruoi
            // Shape layer: "im_emptyBox Outlines" in asset: "Root".
            CompositionContainerShape ContainerShape_00()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(60, 60);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_01());
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            // Group: box
            CompositionContainerShape ContainerShape_01()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(60, 60.1860008F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_02());
                shapes.Add(ContainerShape_03());
                shapes.Add(ContainerShape_04());
                shapes.Add(ContainerShape_05());
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            // Group: Group 10
            CompositionContainerShape ContainerShape_02()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(60, 83.3300018F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_0());
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            // Group: Group 9
            CompositionContainerShape ContainerShape_03()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(76.0719986F, 83.3300018F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_1());
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            // Group: Group 8
            CompositionContainerShape ContainerShape_04()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(60, 55.7480011F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_2());
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            // Group: Group 7
            CompositionContainerShape ContainerShape_05()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(60, 55.75F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_3());
                return result;
            }

            // Root.ruoi
            // Shape layer: "Shape Layer 2" in asset: "Root".
            CompositionContainerShape ContainerShape_06()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(-0.75F, -0.75F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_07());
                return result;
            }

            // Root.ruoi
            //   Root.Shape Layer 2
            // Group: Group 6
            CompositionContainerShape ContainerShape_07()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(67.8700027F, 37.6310005F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_4());
                return result;
            }

            // Shape layer: "ruoi" in asset: "Root".
            CompositionContainerShape ContainerShape_08()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Anchor", new Vector2(60.5309982F, 10.9449997F));
                propertySet.InsertVector2("Position", new Vector2(57.3610001F, 61.0159988F));
                result.CenterPoint = new Vector2(60.5309982F, 10.9449997F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_09());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.Position - my.Anchor";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", Vector2Animation());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Root.ruoi
            // Group: ruoi
            CompositionContainerShape ContainerShape_09()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(60.5309982F, 10.941F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_10());
                shapes.Add(ContainerShape_11());
                shapes.Add(ContainerShape_12());
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            // Group: Group 3
            CompositionContainerShape ContainerShape_10()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(57.9570007F, 10.552F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_5());
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            // Group: Group 2
            CompositionContainerShape ContainerShape_11()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(64.1449966F, 9.60599995F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_6());
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            // Group: Group 1
            CompositionContainerShape ContainerShape_12()
            {
                var result = _c.CreateContainerShape();
                result.Offset = new Vector2(62.4000015F, 13.1440001F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_7());
                return result;
            }

            // Root.ruoi
            //   Root.Shape Layer 2
            //     Group: Group 6
            //       Path 1
            //         Path 1.PathGeometry
            //           TrimEnd
            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.0329999998F), new Vector2(0.833000004F, 0.953000009F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.0329999998F), new Vector2(0.833000004F, 0.967000008F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return _c.CreateCubicBezierEasingFunction(new Vector2(0, 0), new Vector2(0.833000004F, 0.833000004F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_3()
            {
                return _cubicBezierEasingFunction_3 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-32.1430016F, -24.1709995F));
                    builder.AddCubicBezier(new Vector2(-32.1430016F, -24.1709995F), new Vector2(-32.1430016F, 11.3109999F), new Vector2(-32.1430016F, 11.3109999F));
                    builder.AddCubicBezier(new Vector2(-32.1430016F, 11.3109999F), new Vector2(-0.00100000005F, 24.1709995F), new Vector2(-0.00100000005F, 24.1709995F));
                    builder.AddCubicBezier(new Vector2(-0.00100000005F, 24.1709995F), new Vector2(32.144001F, 11.3109999F), new Vector2(32.144001F, 11.3109999F));
                    builder.AddCubicBezier(new Vector2(32.144001F, 11.3109999F), new Vector2(32.144001F, -24.1709995F), new Vector2(32.144001F, -24.1709995F));
                    builder.AddCubicBezier(new Vector2(32.144001F, -24.1709995F), new Vector2(-32.1430016F, -24.1709995F), new Vector2(-32.1430016F, -24.1709995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-16.0720005F, 24.1709995F));
                    builder.AddCubicBezier(new Vector2(-16.0720005F, 24.1709995F), new Vector2(16.0720005F, 11.3120003F), new Vector2(16.0720005F, 11.3120003F));
                    builder.AddCubicBezier(new Vector2(16.0720005F, 11.3120003F), new Vector2(16.0720005F, -24.1709995F), new Vector2(16.0720005F, -24.1709995F));
                    builder.AddCubicBezier(new Vector2(16.0720005F, -24.1709995F), new Vector2(-16.0720005F, -24.1709995F), new Vector2(-16.0720005F, -24.1709995F));
                    builder.AddCubicBezier(new Vector2(-16.0720005F, -24.1709995F), new Vector2(-16.0720005F, 24.1709995F), new Vector2(-16.0720005F, 24.1709995F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(12.8559999F, -23.2490005F));
                    builder.AddCubicBezier(new Vector2(12.8559999F, -23.2490005F), new Vector2(0, -16.6049995F), new Vector2(0, -16.6049995F));
                    builder.AddCubicBezier(new Vector2(0, -16.6049995F), new Vector2(-12.8570004F, -23.2490005F), new Vector2(-12.8570004F, -23.2490005F));
                    builder.AddCubicBezier(new Vector2(-12.8570004F, -23.2490005F), new Vector2(-45, -6.64099979F), new Vector2(-45, -6.64099979F));
                    builder.AddCubicBezier(new Vector2(-45, -6.64099979F), new Vector2(-32.144001F, 0.00100000005F), new Vector2(-32.144001F, 0.00100000005F));
                    builder.AddCubicBezier(new Vector2(-32.144001F, 0.00100000005F), new Vector2(-45, 6.64499998F), new Vector2(-45, 6.64499998F));
                    builder.AddCubicBezier(new Vector2(-45, 6.64499998F), new Vector2(-12.8570004F, 23.2490005F), new Vector2(-12.8570004F, 23.2490005F));
                    builder.AddCubicBezier(new Vector2(-12.8570004F, 23.2490005F), new Vector2(0, 16.6089993F), new Vector2(0, 16.6089993F));
                    builder.AddCubicBezier(new Vector2(0, 16.6089993F), new Vector2(12.8559999F, 23.2490005F), new Vector2(12.8559999F, 23.2490005F));
                    builder.AddCubicBezier(new Vector2(12.8559999F, 23.2490005F), new Vector2(45, 6.64499998F), new Vector2(45, 6.64499998F));
                    builder.AddCubicBezier(new Vector2(45, 6.64499998F), new Vector2(32.1430016F, 0.00100000005F), new Vector2(32.1430016F, 0.00100000005F));
                    builder.AddCubicBezier(new Vector2(32.1430016F, 0.00100000005F), new Vector2(45, -6.64099979F), new Vector2(45, -6.64099979F));
                    builder.AddCubicBezier(new Vector2(45, -6.64099979F), new Vector2(12.8559999F, -23.2490005F), new Vector2(12.8559999F, -23.2490005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-0.00100000005F, -16.6070004F));
                    builder.AddCubicBezier(new Vector2(-0.00100000005F, -16.6070004F), new Vector2(-32.1430016F, -0.00200000009F), new Vector2(-32.1430016F, -0.00200000009F));
                    builder.AddCubicBezier(new Vector2(-32.1430016F, -0.00200000009F), new Vector2(-0.00100000005F, 16.6070004F), new Vector2(-0.00100000005F, 16.6070004F));
                    builder.AddCubicBezier(new Vector2(-0.00100000005F, 16.6070004F), new Vector2(32.144001F, -0.00200000009F), new Vector2(32.144001F, -0.00200000009F));
                    builder.AddCubicBezier(new Vector2(32.144001F, -0.00200000009F), new Vector2(-0.00100000005F, -16.6070004F), new Vector2(-0.00100000005F, -16.6070004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-7.3829999F, 24.7600002F));
                    builder.AddCubicBezier(new Vector2(-12.0579996F, 20.632F), new Vector2(-20.9559994F, 10.8129997F), new Vector2(-7.046F, 5.53999996F));
                    builder.AddCubicBezier(new Vector2(5.76999998F, 0.681999981F), new Vector2(9.79500008F, 1.46099997F), new Vector2(14.3400002F, -2.273F));
                    builder.AddCubicBezier(new Vector2(20.9559994F, -7.71099997F), new Vector2(16.8509998F, -23.5529995F), new Vector2(-3.17799997F, -24.7600002F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0, -3.61400008F));
                    builder.AddCubicBezier(new Vector2(1.99600005F, -3.61400008F), new Vector2(3.61400008F, -1.99600005F), new Vector2(3.61400008F, 0));
                    builder.AddCubicBezier(new Vector2(3.61400008F, 1.99600005F), new Vector2(1.99600005F, 3.61400008F), new Vector2(0, 3.61400008F));
                    builder.AddCubicBezier(new Vector2(-1.99600005F, 3.61400008F), new Vector2(-3.61400008F, 1.99600005F), new Vector2(-3.61400008F, 0));
                    builder.AddCubicBezier(new Vector2(-3.61400008F, -1.99600005F), new Vector2(-1.99600005F, -3.61400008F), new Vector2(0, -3.61400008F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_6()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0.00100000005F, -2.57399988F));
                    builder.AddCubicBezier(new Vector2(1.42200005F, -2.57399988F), new Vector2(2.57399988F, -1.42200005F), new Vector2(2.57399988F, 0));
                    builder.AddCubicBezier(new Vector2(2.57399988F, 1.42200005F), new Vector2(1.42200005F, 2.57399988F), new Vector2(0.00100000005F, 2.57399988F));
                    builder.AddCubicBezier(new Vector2(-1.421F, 2.57399988F), new Vector2(-2.57399988F, 1.42200005F), new Vector2(-2.57399988F, 0));
                    builder.AddCubicBezier(new Vector2(-2.57399988F, -1.42200005F), new Vector2(-1.421F, -2.57399988F), new Vector2(0.00100000005F, -2.57399988F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_7()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-0.00100000005F, -1.801F));
                    builder.AddCubicBezier(new Vector2(0.994000018F, -1.801F), new Vector2(1.801F, -0.995000005F), new Vector2(1.801F, -0.00100000005F));
                    builder.AddCubicBezier(new Vector2(1.801F, 0.992999971F), new Vector2(0.994000018F, 1.801F), new Vector2(-0.00100000005F, 1.801F));
                    builder.AddCubicBezier(new Vector2(-0.995000005F, 1.801F), new Vector2(-1.801F, 0.992999971F), new Vector2(-1.801F, -0.00100000005F));
                    builder.AddCubicBezier(new Vector2(-1.801F, -0.995000005F), new Vector2(-0.995000005F, -1.801F), new Vector2(-0.00100000005F, -1.801F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            LinearEasingFunction LinearEasingFunction()
            {
                return _linearEasingFunction = _c.CreateLinearEasingFunction();
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 10
            //         Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 9
            //         Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 8
            //         Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 7
            //         Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_3()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
                return result;
            }

            // Root.ruoi
            //   Root.Shape Layer 2
            //     Group: Group 6
            //       Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_4()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
                result.TrimEnd = 0;
                result.StartAnimation("TrimEnd", ScalarAnimation_0_to_1());
                var controller = result.TryGetAnimationController("TrimEnd");
                controller.Pause();
                controller.StartAnimation("Progress", ScalarExpressionAnimation());
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            //     Group: Group 3
            //       Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_5()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_5()));
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            //     Group: Group 2
            //       Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_6()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_6()));
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            //     Group: Group 1
            //       Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_7()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_7()));
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0);
                propertySet.InsertScalar("t0", 0);
                var children = result.Children;
                children.InsertAtTop(ShapeVisual());
                result.StartAnimation("t0", ScalarAnimation_1_to_1());
                var controller = result.TryGetAnimationController("t0");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Root.ruoi
            //   Root.Shape Layer 2
            //     Group: Group 6
            //       Path 1
            //         Path 1.PathGeometry
            // TrimEnd
            ScalarKeyFrameAnimation ScalarAnimation_0_to_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, LinearEasingFunction());
                result.InsertKeyFrame(0.699999988F, 1, CubicBezierEasingFunction_0());
                return result;
            }

            ScalarKeyFrameAnimation ScalarAnimation_1_to_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.204379901F, 1, CubicBezierEasingFunction_2());
                result.InsertKeyFrame(0.204380006F, 0, _stepEasingFunction);
                result.InsertKeyFrame(0.388899893F, 1, CubicBezierEasingFunction_3());
                result.InsertKeyFrame(0.388899982F, 0, _stepEasingFunction);
                result.InsertKeyFrame(0.699999928F, 1, _cubicBezierEasingFunction_3);
                return result;
            }

            ExpressionAnimation ScalarExpressionAnimation()
            {
                var result = _scalarExpressionAnimation = _c.CreateExpressionAnimation();
                result.SetReferenceParameter("_", _root);
                result.Expression = "_.Progress";
                return result;
            }

            ShapeVisual ShapeVisual()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(120, 120);
                var shapes = result.Shapes;
                // Root.im_emptyBox Outlines
                shapes.Add(ContainerShape_00());
                // Root.Shape Layer 2
                shapes.Add(ContainerShape_06());
                // Root.ruoi
                shapes.Add(ContainerShape_08());
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 10
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = ColorBrush_AlmostLightGray_FFCCD1D9();
                result.Geometry = PathGeometry_0();
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 9
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = ColorBrush_AlmostLavender_FFE6E9EC();
                result.Geometry = PathGeometry_1();
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 8
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = ColorBrush_AlmostWhiteSmoke_FFF4F4F4();
                result.Geometry = PathGeometry_2();
                return result;
            }

            // Root.ruoi
            //   Root.im_emptyBox Outlines
            //     Group: box
            //       Group: Group 7
            // Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = _colorBrush_AlmostLightGray_FFCCD1D9;
                result.Geometry = PathGeometry_3();
                return result;
            }

            // Root.ruoi
            //   Root.Shape Layer 2
            //     Group: Group 6
            // Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                var result = _c.CreateSpriteShape();
                result.Geometry = PathGeometry_4();
                result.StrokeBrush = AnimatedColorBrush_AlmostDarkGray_FF9F9F9F_to_TransparentAlmostDarkGray_009F9F9F();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                var strokeDashArray = result.StrokeDashArray;
                strokeDashArray.Add(2.02800012F);
                strokeDashArray.Add(2.02800012F);
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 4;
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            //     Group: Group 3
            // Path 1
            CompositionSpriteShape SpriteShape_5()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = AnimatedColorBrush_White_to_TransparentWhite();
                result.Geometry = PathGeometry_5();
                result.StrokeBrush = AnimatedColorBrush_AlmostGray_FF868686_to_TransparentAlmostGray_00868686();
                result.StrokeMiterLimit = 10;
                result.StrokeThickness = 0.699999988F;
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            //     Group: Group 2
            // Path 1
            CompositionSpriteShape SpriteShape_6()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = _animatedColorBrush_White_to_TransparentWhite;
                result.Geometry = PathGeometry_6();
                result.StrokeBrush = _animatedColorBrush_AlmostGray_FF868686_to_TransparentAlmostGray_00868686;
                result.StrokeMiterLimit = 10;
                result.StrokeThickness = 0.699999988F;
                return result;
            }

            // Root.ruoi
            //   Group: ruoi
            //     Group: Group 1
            // Path 1
            CompositionSpriteShape SpriteShape_7()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = _animatedColorBrush_AlmostGray_FF868686_to_TransparentAlmostGray_00868686;
                result.Geometry = PathGeometry_7();
                return result;
            }

            StepEasingFunction StepEasingFunction()
            {
                var result = _stepEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame  = true;
                return result;
            }

            // Root.ruoi
            // Position
            Vector2KeyFrameAnimation Vector2Animation()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.SetReferenceParameter("_", _root);
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(57.3610001F, 61.0159988F), _linearEasingFunction);
                result.InsertExpressionKeyFrame(0.204379901F, "(Pow(1 - _.t0, 3) * Vector2(57.361,61.016)) + (3 * Square(1 - _.t0) * _.t0 * Vector2(52.686,56.88799)) + (3 * (1 - _.t0) * Square(_.t0) * Vector2(43.78901,47.069)) + (Pow(_.t0, 3) * Vector2(57.699,41.796))", StepEasingFunction());
                result.InsertExpressionKeyFrame(0.388899893F, "(Pow(1 - _.t0, 3) * Vector2(57.699,41.796)) + (3 * Square(1 - _.t0) * _.t0 * Vector2(70.515,36.938)) + (3 * (1 - _.t0) * Square(_.t0) * Vector2(74.53902,37.716)) + (Pow(_.t0, 3) * Vector2(79.084,33.982))", _stepEasingFunction);
                result.InsertExpressionKeyFrame(0.699999928F, "(Pow(1 - _.t0, 3) * Vector2(79.084,33.982)) + (3 * Square(1 - _.t0) * _.t0 * Vector2(85.70001,28.544)) + (3 * (1 - _.t0) * Square(_.t0) * Vector2(79.72001,10.328)) + (Pow(_.t0, 3) * Vector2(59.691,9.121))", _stepEasingFunction);
                result.InsertKeyFrame(0.700000048F, new Vector2(59.6910019F, 9.12100029F), _stepEasingFunction);
                return result;
            }

            Instantiator(Compositor compositor)
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
            }

            public static Visual InstantiateComposition(Compositor compositor)
                => new Instantiator(compositor).Root();
        }
    }
}
